#!/usr/bin/env python
# -*- charset: utf-8 -*-
# vim: sts=4 sw=4 et

import sys
from streetmangler import Locale, Database
import lxml.etree as ET

if len(sys.argv) < 3:
    print "Usage: %s db.txt file.osm" % sys.argv[0]
    sys.exit(1)

db = Database(Locale('ru_RU'))
db.Load(sys.argv[1])

if sys.argv[2] == '-':
    fp = sys.stdin
else:
    fp = open(sys.argv[2])

xml = ET.parse(fp)

cache = {}
for t in xml.xpath('//tag[@k="addr:street"]'):
    street = t.attrib['v'].encode('utf-8')
    if not street:
        continue
    if street in cache:
        t.attrib['v'] = cache[street]
        continue
    canonical = db.CheckCanonicalForm(street)
    if not canonical:
        continue
    #print "%s -> %s" % (street, ', '.join(canonical))
    t.attrib['v'] = cache[street] = canonical[0].decode('utf-8')

print ET.tostring(xml, encoding='utf-8')

